ZCS-499/Bug-107044:SIEVE:default comparator
'address' test compared the value not asciily but numerically
if the comparator was not specified.

[Bug]
The following sieve script fails due to the the FeatureException
exception:
org.apache.jsieve.exception.FeatureException: Substring match unsupported by ascii-numeric

```
if address :matches ["to"] "*" {
 ...
}
```
[Root cause]
"i;ascii-numeric" is used as a default comparator.

[Fix]
Use "i;ascii-casemap" when the match type is ":is", ":matches",
or ":contains".  RFC 5228 Section 2.7.3. says
  ---
  If left unspecified, the default is "i;ascii-casemap".
  ---

(Note) By the way, although the RFC 5231 "Relational Extension"
does not mention explicitly about which comparator should be used
when it is not specified, as a nature of the match type, ":count"
and ":value" should take "i;ascii-numeric" as a default comparator.
As it has already implemented correctly, we do not have to fix
that part.

[Affected Area]
ZCS - SIEVE processor - 'address' test with ":is", ":matches", or
":contains" match type

[Unit test]
The following unit tests were successfully passed:
- AddressTest