ZCS-3055:TestJaxb test
Renamed test `testAcceptSeriesDeclineInstance()`
`acceptAndTentativeSeriesDeclineInstanceAcceptInstance()`

Also enhanced it to check for fix to ZCS-3055.
Quite a lot of refactoring for shared code, using realistic dates.

Test fails on develop before ZCS-3055 fix with:
    number of components in exception expected:<1> but was:<2>
    from TestJaxb.validateException(TestJaxb.java:474)

because:

    <GetMsgRequest xmlns="urn:zimbraMail">
      <m ridZ="20190206T140000Z" id="258-0"/>
    </GetMsgRequest>

returns 2 components:
one with start time:

    <s d="20190206T140000Z" u="1549461600000"/>

and the other with start time:

    <s d="20190210T140000Z" u="1549807200000"/>

clearly, the 2nd component shouldn't be there and that is one side
effect of the bug.