bug: 63863 - CreateSystemRetentionPolicyRequest accepts negative values for lifetime.
Updated time duration parsing code so that it rejects negative values.

------------

$ zmsoap -z CreateSystemRetentionPolicyRequest/purge/policy @lifetime="-2d" @name="abc" @xmlns=urn:zimbraMail
ERROR: service.INVALID_REQUEST (invalid request: Invalid lifetime value: -2d)

http://bugzilla.zimbra.com/show_bug.cgi?id=63863

Copied from Perforce
 Change: 331438