(split)Bug 101247 - SearchGalRequest "endswith" operator of the condition does not work due to the incorrect parsing
When GAL search is performed to the internal synced GAL account, the server does not parse the search query that contains the conditions with "endswith" operator; the close parenthesis was missing.
Add ")" at the end of the internal query string when the operator is "endswith".

[Test]
Create a domain with GAL sync account.  Create some accounts on that domain, and force-sync the GAL.
Submit the following request (zmsoap -m your_test_user_account -p your_password --json -f file_name_of_request_string_below)
 ---
  { SearchGalRequest: { _jsns: "urn:zimbraAccount", limit: 50, locale: { _content: "en_US" }, field: "to", name: "sample1", needExp: 1, needIsMember: "directOnly", needIsOwner: "1", offset: 0, searchFilter: { conds: { conds: [ { cond: [ { attr: "to", op: "endswith", value: "sample109@galsync.com" }, { attr: "email", op: "endswith", value: "sample108@galsync.com" } ], or: 1 } ] } }, sortBy: "nameAsc", type: "account" } }
 ---

Tail the mailbox.log and no WARN even is logged.

(Before fix, the following event should be logged
.........
2015-09-11 16:40:30,385 WARN  [qtp926434463-91] [name=sample110@galsync.com;ip=127.0.0.1;ua=zmsoap;] gal - search on GalSync account failed for 4d667c36-27bc-4bbd-9858-76b7055641a8
com.zimbra.cs.mailbox.MailServiceException: Couldn't parse query: contact:"sample101" AND (((#to:(*sample101 OR #email:(*sample101))) AND( inid:257) AND !(#zimbraAccountCalendarUserType:RESOURCE)
ExceptionId:qtp926434463-91:1441957230384:bc954178647797f2
Code:mail.QUERY_PARSE_ERROR Arg:(curTok, STR, "OR") Arg:(colNo, NUM, "44") Arg:(parserErr, STR, "Encountered " <FIELD> "#email: "" at line 1, column 47.
Was expecting one of:
    "(" ...
    <NOT> ...
    "+" ...
    "-" ...
    <TERM> ...
    <QUOTED_TERM> ...
    ")
	at com.zimbra.cs.mailbox.MailServiceException.QUERY_PARSE_ERROR(MailServiceException.java:481)
	at com.zimbra.cs.index.query.parser.QueryParser.parse(QueryParser.java:316)
	at com.zimbra.cs.index.ZimbraQuery.<init>(ZimbraQuery.java:378)
	at com.zimbra.cs.mailbox.MailboxIndex.search(MailboxIndex.java:164)
	at com.zimbra.cs.gal.GalSearchControl.doLocalGalAccountSearch(GalSearchControl.java:444)
.........
)

https://bugzilla.zimbra.com/show_bug.cgi?id=101247

Copied from Perforce
 Change: 555015