bug:98315
AuthResponse JAXB invalid
When running "ant wsdl-test" getting several failures like this for WSDLCalendaringTest.createTask

javax.xml.ws.WebServiceException: com.sun.istack.SAXParseException2; org.xml.sax.SAXParseException; cvc-complex-type.2.4.b: The content of element 'AuthResponse' is not complete. One of '{"urn:zimbraAccount":trustLifetime, "urn:zimbraAccount":session, "urn:zimbraAccount":refer, "urn:zimbraAccount":csrfToken, "urn:zimbraAccount":deviceId, "urn:zimbraAccount":trustedToken, "urn:zimbraAccount":prefs, "urn:zimbraAccount":attrs}' is expected.
at com.sun.xml.ws.util.pipe.AbstractSchemaValidationTube.doProcess(AbstractSchemaValidationTube.java:242)
at com.sun.xml.ws.util.pipe.AbstractSchemaValidationTube.processResponse(AbstractSchemaValidationTube.java:220)
...

Root cause is that you cannot use primitive types for optional elements/attributes (because we need null to represent absence)
https://reviewboard.eng.zimbra.com/r/4867/

https://bugzilla.zimbra.com/show_bug.cgi?id=98315

Copied from Perforce
 Change: 544017