ZCS-5930: Re-added the overriding finalze() method
to ensure that the file descriptor gets closed when this object is garbage collected because of the
javax.mail.MessagingException: IOException: Stale file handle. As we have no control over how JavaMail
uses BlobInputStream. Also, as compared to earlier code the finalizer is wrapped inside a try-finally
block as finalizers are not very predictable and if we have to use we should put the super.finalize()
in a try-finally block which ensures that the superclass finalizer will be called even if some exception
is thrown.