(split)bug:55509 Workaround StringIndexOutOfBoundsException due to a JavaMail bug
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1937)
        at javax.mail.internet.InternetAddress.unquote(InternetAddress.java:367)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1013)
        at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:600)

https://reviewboard.eng.vmware.com/r/199983/

http://bugzilla.zimbra.com/show_bug.cgi?id=55509

Copied from Perforce
 Change: 269970