bug: 103310 Invalid characters in XML causing failure in parsing.
Exception details:
org.xml.sax.SAXException: Fatal Error: Problem on line 1 of document : An invalid XML character (Unicode: 0x1b) was found in the value of attribute "p" and element is "e".

Root cause:
Invalid characters in XML was causing SAX parsing to fail.

Fix:
Exising functionality of XML validation inside Element.java is refactored by adding couple of methods - isValidXmlCharacter( ) and isSupplementaryCharacter( ).

Link for valid set of XML characters - https://en.wikipedia.org/wiki/Valid_characters_in_XML

Added couple of Junit test cases to validate newly added functions.

https://bugzilla.zimbra.com/show_bug.cgi?id=103310

Copied from Perforce
 Change: 565972