(split)bug: 57222 - SendMsgRequest: uploaded file not on disk
If an Upload references a file that's been deleted, log
a better error message when the caller attempts to
get the content:

Caused by: com.zimbra.cs.mailbox.MailSender$SafeSendFailedException: MESSAGE_NOT_DELIVERED; chained exception is:
	java.io.IOException: Cannot get content for upload 89fc7f63-40b6-4afb-ba33-0a02c3b75104:ddc5cafe-70c7-4061-a799-0ac6080fe461 because it was deleted.

http://bugzilla.zimbra.com/show_bug.cgi?id=57222

Copied from Perforce
 Change: 281559