ZCS-4759:MailboxTransaction tidy
For HA, have generally replaced:

        try {
            beginTransaction(...);
            ...
            success = true;
        } finally {
            endTransaction(success);
        }

With:

        try (final MailboxTransaction t = new MailboxTransaction(...)) {
            ...
            t.commit();
        }

In the old code, if `beginTransaction` throws an exception, then
`endTransaction` will be called.
In the new code, if the `MailboxTransaction` constructor throws an
exception then the new equivalend of `endTransaction` (`close`) will not
be called.
This is almost certainly the root cause of this exception:

    ServiceException: system failure: cannot start a logged transaction from within another transaction

as this happens when MailboxChange.depth is too high and that would be
consistent with MailboxChange.depth being incremented in the constructor
and then not being decremented because `endTransaction` was not called.