ZCS-1006:rework(2):"i;ascii-numeric" doesn't handle negative number
[Bug]
NoClassDefFoundError exception was thrown.

[Fix]
Use com.zimbra.common.util.StringUtil.isNullOrEmpty() instead of org.hsqldb.lib.StringUtil.isEmpty()

[Unit test]
EnvelopeTest, AddressTest: PASS