bug: 22927
- added a mId member (exception id) of ServiceException.  It is in the format of:
  {server-name}:{thread-name}:{timestamp}:{16-byte random hex}

- modified ServiceException.toString() to include the mId.   The log will look like:
2008-02-01 10:38:40,362 INFO  [btpool0-24] [name=user1@phoebe.local;ip=127.0.0.1;] SoapEngine - handler exception
com.zimbra.cs.account.AccountServiceException: no such signature: blahblah
ExceptionId:phoebe.local:btpool0-24:1201891120361:1b090c89576c9812
Code:account.NO_SUCH_SIGNATURE
	at com.zimbra.cs.account.AccountServiceException.NO_SUCH_SIGNATURE(AccountServiceException.java:185)
	at com.zimbra.cs.service.account.ModifySignature.handle(ModifySignature.java:51)
                  ...


- modified all SoapProtocol.soapFault(ServiceException) to fill the <trace> tag with e.getId(), instead of the stack.

- for now ServiceException.getId() still returns the stack, not the mId, so the behavior is unchanged for now(i.e. stack gets returned in SoapFault).    Will switch to returning exception id after other bits of the bug (comment #6 and #10) are checked in.

http://bugzilla.zimbra.com/show_bug.cgi?id=22927

Copied from Perforce
 Change: 82202