ZCS-611/Bug-107562:SIEVE:parse error by "require"
SIEVE: the string text "require" inside the filter rule
is mistakenly cut&pasted to the top of the filter

[Bug]
If the filter script contains a parameter whose value matches
the text "require", then the SIEVE execution is failed to
parse the filter by the exception "Parse failed.".

For example, when the following sieve rule is set:
require ["log"];
if  header :contains ["Subject"] "require abc def" {
  log "--- require ---";
}

then you will see the following log event (with debug log)
2017-01-25 23:52:30,423 WARN  [LmtpServer-1] [name=kinugasa@ykomiyam.local;mid=57;ip=192.168.59.199;] filter - An error occurred while processing filter rules. Filing message to /Inbox.
org.apache.jsieve.parser.generated.TokenMgrError: Lexical error at line 2, column 8.  Encountered: "-" (45), after : ""
...

According to the debug log, any text "require" appeared after
the regular "require" action are cut and pasted at the end
of the original "require" action.

[Root cause]
It was introduced by the rework of the Bug 104912; it
combines three sieve scripts (zimbraMailAdminSieveScriptBefore,
zimbraMailSieveScript, and zimbraMailAdminSieveScriptAfter)
into one script.  Before combining, each SIEVE filter is
split into "require" action part and other actions part,
and all "require" action parts are put at the top of the
combined SIEVE rule. The bug was in the method of extracting
the "require" action parts.

[Fix]
Pick only the "require ... ;" block which exists at the top of
each filter script.

[Unit test]
The following unit tests are passed successfully:
test-com.zimbra.cs.filter.AddHeaderTest
test-com.zimbra.cs.filter.DeleteHeaderTest
test-com.zimbra.cs.filter.EnvelopeTest
test-com.zimbra.cs.filter.FilterUtilTest
test-com.zimbra.cs.filter.NotifyMailtoTest
test-com.zimbra.cs.filter.ReplaceHeaderTest
test-com.zimbra.cs.filter.RuleManagerAdminFilterTest
test-com.zimbra.cs.filter.SetVariableTest
test-com.zimbra.cs.filter.FileIntoCopyTest
test-com.zimbra.cs.filter.TagTest
test-com.zimbra.cs.filter.RedirectCopyTest
test-com.zimbra.cs.filter.FlaggedTestTest
test-com.zimbra.cs.filter.RelationalExtensionTest

[Affected area]
MBS - all SIEVE action (parsing sieve filter)

(cherry picked from commit d9e582785c2e9ad3b9aebc9cb3c34a6c07b68a32)